title: Your Site Title
description: A brief description of your project/site
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Optional but recommended settings for Architect theme
show_downloads: false
theme: architect
