title: Elizabeth daily dose of smartness 
description: To get anything you need to put work and time. The more you put now - the more you get later. Stay smart - stay ahead.
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Optional but recommended settings for Architect theme
show_downloads: false
theme: architect
